# Generated by Django 5.0.6 on 2024-12-15 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_options_alter_pictures_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 22, 30, 15, 338080), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 22, 30, 15, 343162), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 22, 30, 15, 343162), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к картинке'),
        ),
    ]
