# Generated by Django 5.0.6 on 2024-12-17 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_articles_data_alter_comments_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 11, 45, 31, 656430), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 11, 45, 31, 656430), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 11, 45, 31, 656430), verbose_name='Дата публикации'),
        ),
    ]
