# Generated by Django 5.2 on 2025-04-21 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_articles_data_alter_comments_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('job', models.CharField(max_length=100, verbose_name='Род деятельности')),
                ('gender', models.CharField(choices=[('1', 'Мужчина'), ('2', 'Женщина')], max_length=10, verbose_name='Пол')),
                ('internet', models.CharField(choices=[('1', 'Ежедневно'), ('2', 'Пару часов в день'), ('3', 'Пару часов в неделю'), ('4', 'Пару часов в месяц')], max_length=20, verbose_name='Использование интернета')),
                ('notice', models.BooleanField(default=False, verbose_name='Получать новости на e-mail')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 12, 26, 4, 942239), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 12, 26, 4, 943239), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 12, 26, 4, 943239), verbose_name='Дата публикации'),
        ),
    ]
