# Generated by Django 5.2 on 2025-04-27 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_feedback_alter_articles_data_alter_comments_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 0, 50, 12, 473854), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 0, 50, 12, 473854), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 0, 50, 12, 473854), verbose_name='Дата публикации'),
        ),
    ]
