# Generated by Django 5.0.6 on 2024-12-15 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitems',
            name='count',
        ),
        migrations.RemoveField(
            model_name='shopitems',
            name='onePerUser',
        ),
        migrations.AlterField(
            model_name='orders',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 22, 49, 7, 481099), verbose_name='Дата заказа'),
        ),
    ]
