# Generated by Django 5.0.6 on 2024-12-17 00:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shopitems_count_remove_shopitems_oneperuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='data',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='items',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 3, 28, 43, 825886), verbose_name='Дата заказа'),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='cartitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('shopitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopitems', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'товар корзины',
                'verbose_name_plural': 'товары корзины',
            },
        ),
        migrations.CreateModel(
            name='orderitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена на момент заказа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders', verbose_name='Заказ')),
                ('shopitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopitems', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'товар заказа',
                'verbose_name_plural': 'товары заказа',
            },
        ),
    ]
