# Generated by Django 5.0.6 on 2024-12-17 08:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_categories_alter_orders_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'статус заказа',
                'verbose_name_plural': 'cтатусы заказов',
            },
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 11, 40, 44, 46278), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.statuses', verbose_name='Статус заказа'),
        ),
    ]
