# Generated by Django 5.0.6 on 2024-12-17 08:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_statuses_alter_orders_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 11, 45, 31, 676447), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.statuses', verbose_name='Статус заказа'),
        ),
    ]
