# Generated by Django 5.0.6 on 2024-12-17 09:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orders_order_date_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 12, 8, 33, 457191), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.statuses', verbose_name='Статус заказа'),
        ),
    ]
