# Generated by Django 5.2 on 2025-04-21 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_orders_order_date_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 12, 26, 4, 947239), verbose_name='Дата заказа'),
        ),
    ]
