# Generated by Django 5.2 on 2025-04-27 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 0, 50, 12, 476879), verbose_name='Дата заказа'),
        ),
    ]
